default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: quang_huy
  password: <%= ENV['passpg'] %>

development:
  <<: *default
  database: rencar_development

test:
  <<: *default
  database: rentcar_test

production:
  <<: *default
  database: rentcar_production