development:
  adapter: postgresql
  encoding: unicode
  database: rencar_development
  pool: 5
  username: quang_huy
  password: q12122211234

test:
  adapter: postgresql
  encoding: unicode
  database: rentcar_test
  pool: 5
  username: quang_huy
  password: q12122211234

production:
  adapter: postgresql
  encoding: unicode
  database: rentcar_production
  pool: 5
  username: quang_huy
  password: q12122211234